# Generated by Django 3.0.7 on 2020-06-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_price',
            field=models.FloatField(default=0),
        ),
    ]
