# Generated by Django 3.0.5 on 2020-05-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='code_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
