# Generated by Django 3.0.5 on 2020-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_promocode_code_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('corresponding', models.CharField(max_length=1000)),
                ('payment_mode', models.BooleanField()),
            ],
        ),
    ]
