# Generated by Django 3.0.5 on 2020-05-29 13:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_checkoutform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutform',
            name='payment_mode',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkoutform',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
