# Generated by Django 3.0.7 on 2020-06-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not order', 'not order'), ('Out for delivery', 'Out for delivery'), ('delivered', 'delivered')], default='not order', max_length=100),
        ),
    ]
