# Generated by Django 3.0.5 on 2020-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200529_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutform',
            name='payment_mode',
            field=models.BooleanField(blank=True, default=''),
        ),
    ]
