# Generated by Django 3.0.5 on 2020-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200529_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutform',
            name='payment_mode',
            field=models.CharField(max_length=100),
        ),
    ]
