# Generated by Django 3.0.7 on 2020-06-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status']},
        ),
    ]
