# Generated by Django 3.0.7 on 2020-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200609_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not order', 'not order'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='not order', max_length=100),
        ),
    ]
