# Generated by Django 3.0.5 on 2020-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutform',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='checkoutform',
            name='cash_on_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutform',
            name='credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutform',
            name='debit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutform',
            name='online_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutform',
            name='paypal',
            field=models.BooleanField(default=False),
        ),
    ]
