# Generated by Django 3.0.7 on 2020-06-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200609_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-status']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not order', 'not order'), ('out for delivery', 'out for delivery'), ('Delivered', 'Delivered')], default='not order', max_length=100),
        ),
    ]
