# Generated by Django 3.0.5 on 2020-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200530_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutform',
            name='cash_on_delivery',
        ),
        migrations.RemoveField(
            model_name='checkoutform',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='checkoutform',
            name='debit_card',
        ),
        migrations.RemoveField(
            model_name='checkoutform',
            name='online_payment',
        ),
        migrations.RemoveField(
            model_name='checkoutform',
            name='paypal',
        ),
        migrations.AddField(
            model_name='checkoutform',
            name='payment_mode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
