# Generated by Django 3.0.7 on 2020-06-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200609_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='order',
            name='unique_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
