# Generated by Django 3.0.7 on 2020-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200609_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
