# Generated by Django 3.0.7 on 2020-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
