# Generated by Django 3.0.7 on 2020-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
