# Generated by Django 3.0.7 on 2020-06-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20200623_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Like'),
        ),
    ]
