# Generated by Django 3.0.7 on 2020-06-23 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0020_comments_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
