# Generated by Django 3.0.7 on 2020-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200623_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
