# Generated by Django 3.0.7 on 2020-06-24 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0023_auto_20200623_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_sno', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_reply', models.TextField()),
                ('user', models.CharField(max_length=20)),
                ('total_liked', models.IntegerField(default=0)),
                ('total_disliked', models.IntegerField(default=0)),
                ('reply_time', models.DateTimeField()),
                ('disliked', models.ManyToManyField(related_name='disliked', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('on_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Reply_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_likes', models.IntegerField(default=0)),
                ('like_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Reply')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply_dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_dislikes', models.IntegerField(default=0)),
                ('dislike_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Reply')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='all_reply',
            field=models.ManyToManyField(related_name='reply', to='myapp.Reply'),
        ),
    ]
