# Generated by Django 3.0.7 on 2020-06-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200624_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_like',
            name='like_reply',
        ),
        migrations.RemoveField(
            model_name='reply_like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reply_dislike',
        ),
        migrations.DeleteModel(
            name='Reply_like',
        ),
    ]
